### PR TITLE
add js-interop example

### PR DESCRIPTION
**Pull request by thheller**
Just plain js-interop, no libraries or other utils used.

Didn't update README with numbers since they look quite different on my machine compared to the others, but it is the fastest of them all.

### CODE REVIEW

**Comment by thheller** [comment]
Using `js-await` since I'm a bit allergic to promesa `p/let`. That was also the cause you didn't see the failures when trying my code snippet I guess. There was never any `.catch` being done in the examples, so any errors just disappear.

**Comment by thheller** [comment]
compiled demo: https://code.thheller.com/demos/js2clj2js/

**Comment by PEZ** [comment]
Thanks, Thomas! This is super for the purpose of the article/project. I'll update the README.

> Using js-await

TIL. I'll check it out! And probably switch to `js-await` for all examples.

> That was also the cause you didn't see the failures when trying my code snippet I guess. There was never any .catch being done in the examples, so any errors just disappear.

You mean that Promesa swallows the error? I thought that if I didn't catch an error, it would blow things up and be seen in the console. I clearly must fill in some knowledge gaps here.

**Comment by thheller** [comment]
> You mean that Promesa swallows the error?

Seemed like it. I first had `p/let` and a nil access in my transform fn. It just failed silently. Since I didn't know how to add error handling to `p/let` I switched to `js-await` and added the `catch`, which got me the error being logged to the console. I'm sure you can do that with promesa too, I just didn't know how.

**Comment by PEZ** [comment]
I now [added a Promesa catch in that other branch](https://github.com/PEZ/js2clj2js/commit/34081c307524ccefc9efc0984fa6bffbdd2215bb?diff=unified&w=1). That exposes the error. It was a surprise to me that the error otherwise gets swallowed. That's weird! But now I know. Thanks for pointing it out!

**Comment by PEZ** [comment]
I got curious about how much faster the raw JS interop was so made some tests where I loop over the transform step 1K and 10K times. It's pretty significant:

https://github.com/PEZ/js2clj2js?tab=readme-ov-file#transform-performance

Also very strange with the data getting corrupted for all JS data solutions when I do this looping...

**Comment by thheller** [comment]
FWIW you can change my `close-polygon` implementation to this, which first clones the array, leaving the initial array untouched.

```
(defn close-polygon [coords]
  (if-not (pos? (alength coords))
    coords
    #js [(doto (.slice coords)
           (.push (aget coords 0)))]))
```

A bit slower than not doing that of course, but still quite a lot faster than any of the `clj->js` variations.

Calling this "corrupted" is a bit harsh, since this is completely expected and normal behavior for mutable data. I mean it makes a good argument for why CLJS datastructures make sense, but as seen in your numbers it also shows what that costs.

**Comment by PEZ** [comment]
> Calling this "corrupted" is a bit harsh, since this is completely expected and normal behavior for mutable data.

Yes, I'll try to reword it now that I better understand it.

**Comment by PEZ** [comment]
Thanks for your updated close-polygon. Though I think I need to rethink the “benchmark” approach. The update is only needed because the benchmarking needs it, right? I mean, in a real app for the given scenario, you would only go over the polygons once anyway.

Not that I know how to set things up better. I could also define the repeated transformto be part of the transfrom task and let it impact all implementations that need it...

**Comment by thheller** [comment]
I don't know what you are intending to show with the benchmark.

I mean it should be obvious that mutating an object is faster than doing a deep clone and (possibly) transforming it to a persistent datastructure (and back). Mutating also implies that this is not just a randomly repeatable operation.

In real world apps it may be a requirement that the input data is not mutated, and things be repeatable. So you'd copy/clone the parts that would otherwise be mutated. If it not a requirement you can save that work and gain some performance. 

You could make a fresh copy of the entire structure before calling the transform for benchmark purposes, but creating a full copy would almost certainly become the bottleneck of such a benchmark.

Requirements vary and I don't think there is anything valuable to learn from such a benchmark comparison in this context. There definitely is a point where keeping all data persistent and NOT having to perform a fresh clone every time begins to outweigh the cost of going persistent once. I don't think any app would ever reach that point for a struct like yours, given that the major cost of transforming all the polygon coordinate arrays and you'd generally not mutate them.

**Comment by PEZ** [comment]
My purpose would be to get a clearer picture what the tradeoffs are. In this case I wanted to get an idea about the performance overhead of using a wrapper library instead of doing it like you do. The ergonomics are in plain sight. I much prefer the **js-mode** code over all that `unchecked-get` stuff. But somewhere the convenience will cost more performance than I can afford. The demo app doesn't come near that trade-off, so I was curious about when that would happen.

**Comment by PEZ** [comment]
Also. To the point of things being obvious. I was super surprised to see that doing the transform 10K times would take about no time at all using Clojure immutable data structures. While it seems to take a significant amount of time with JS mutable data. Then when you made me realize that the polygons keep growing I started to suspect I had caused the JS data mutation way to be that much slower. I'll probably try to use your updated code and see how CLJ and JS data transforming compares then for this example.

**Comment by thheller** [comment]
I personally would never even consider something like `js-mode`, but I don't mind interop in general when it makes sense.

I do acknowledge that destructuring looks a bit nicer, so something like

```clojure
(defn- bigmac-etc->feature
  [{:js/strs [country-name points] :as json-data}]
  ...)
```
would certainly look nice, where `:js/strs` would map to `json_data["country-name"]`, or `{:js/keys [x] :as obj}` would map to `obj.x`. 

Technically there is no reason we couldn't have destructuing for JS objects like that. It won't even break any core language specs, just of course wouldn't work for CLJ. I have never personally pursued getting this into cljs.core, since as I said I don't mind interop and pretty much never need it myself.

**Comment by thheller** [comment]
FWIW if you really cared about performance and want to avoid UI locking as much as possible you could move all fetch/translation code into a webworker and have the regular UI code just work with the already processed JS object with no conversion ever happening in the UI code.

I of course didn't test this, but I suspect that UI could get the UI locktime for parsing down to less than 5msec + whatever time it takes to render this data. This is extremely app specific though, so while it makes sense here, it probably won't be for many other apps.

**Comment by PEZ** [comment]
I would love to be able to destruct like you describe there. As you have noted, I can go to quite some length to get something similar to happen.

**Pull request merged**
